# fix and copy this to setup.toml

# including trailing slash
baseurl = "http://my.domain/my/crowdsourcing/"

mailname = "My Crowdsourcing"
mailfrom = "me@my.domain"

# leave this empty if the mail server doesn't need log in
smtpuser = ""
smtppass = ""

smtpserv = "smtp.xs4all.nl:25"
